### ISSUE TITLE
ObjectDisposedException on many to many

### ISSUE THREAD

**Issue by voodookoop** [darxis/EntityFramework.LazyLoading#3] opened 2017-04-04 11:07 UTC
Hi, Consider the following case:

            using (var dbContext = lazyFactory.Create(factoryOptions))
            {
                try
                {
                    var instructorAbercrombie = dbContext.Set<Instructor>().First(x => x.LastName == "Abercrombie");

                    var coursesOfinstructorAbercrombie = instructorAbercrombie.CourseAssignments.Select(x => x.Course);

                    var courseCount = coursesOfinstructorAbercrombie.Count();

                    Console.WriteLine($"Instructor Abercrombie has {courseCount} courses.");
                }
                catch (ObjectDisposedException)
                {
                    Console.WriteLine($"{nameof(ObjectDisposedException)} occured (ConcurrencyDetector).");
                }
            }

you can reproduce the exception based on this.

**Comment by voodookoop** [comment] 2017-04-04 14:02
@darxis : maybe you also figured out, that this basically has nothing to do with many to many, just simply creating another lazied dbContext, then querying a lazied prop will bring up the ObjectDisposedException.

**Comment by darxis** [comment] 2017-04-04 14:17
@voodookoop Thanks for reporting an issue!

I figured out that EF Core is caching Expressions for materializing entities. In LazyLoading, such expression contains the DBContext. So the problem is that when you create another DBContext, the old materializing expressions are cahced, and they contain the old (Disposed) DBContext. I'm gonna try to fix it until the end of the day.

**Comment by darxis** [comment] 2017-04-04 18:53
Closing as it is fixed in release 1.1.1-beta2, now available on NuGet.

Also note that in the new release you need to add two more lines of code to your configuration (they are present in the sample project and in the README.md)

**Closed as completed by darxis** 2017-04-04 18:53 UTC
Labels: bug
